version: '3'
services:
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: crunchy
      RABBITMQ_DEFAULT_PASS: killah
    ports:
      - 5672:5672
      - 15672:15672